### ISSUE TITLE
[setup][docker] Est ce qu'une version docker est disponible?

### ISSUE THREAD

**Issue by yanis-git** [Tanaguru/tanaguru2020-engine#142]
Bonjour, 

J'aimerai savoir si il y a une version docker du ou des projets comme un docker-compose ou autre ? 

Merci d'avance !

**Comment by remy56k** [comment]
👋 @yanis-git, je suis en train de faire une stack PostgreSQL + tanaguru2020-engine + tanaguru2020-webapp sur la base de la release 2.1.0, si tout fonctionne correctement, je pourrais la transmettre.

**Comment by yanis-git** [comment]
Super ! Merci 🙏

Je peux prêter main forte si tu en sents le besoin.

**Comment by zwiastunsw** [comment]
@remy56k Bonjour, avez-vous réussi à créer une version sur Docker ? Pourriez-vous la partager ?

**Comment by remy56k** [comment]
Au final, j'ai fais tourner la stack en utilisant les sources fournies ici : https://gitlab.com/asqatasun/asqatasun-docker
Je suis pour le moment en v5, il faudrait que je migre en v6.

**Comment by fhalna** [comment]
Not a issue
