### ISSUE TITLE
Vue Référentiel - résultats mélangés

### ISSUE THREAD

**Issue by nmadeuf** [Tanaguru/tanaguru2020-engine#52]
Il semblerait que lorsqu'un critère indique des critères invalidés, si l'on affiche les résultats pour ce critère, il y ait des mélanges avec d'autres critères. 
Ex: 
![image](https://user-images.githubusercontent.com/41478857/113716526-fdd46180-96ea-11eb-813e-842ddfbe8098.png)

Lien vers l'audit concerné: https://dev.tanaguru.com/#/audits/364/pages/4178/-1497760085

**Comment by rcharre** [comment]
@rgervois-oceane  Dans les tests de la webext, le test sur la liste des champs de formulaires est taggé pour 10.1.2 est ce que c'est normal ?
