### ISSUE TITLE
Eléments non présents indiqués valides

### ISSUE THREAD

**Issue by nmadeuf** [Tanaguru/tanaguru2020-engine#57]
@rgervois-oceane , dans la webextension (et donc dans tanaguru engine), certains critères sont validés pour des éléments n'étant pas présents dans la page. Ex.: pour le critère 1.1.3, le test "Liste de boutons de type image (balise input avec l‘attribut type="image") Sans nom accessible ?" alors que je n'ai pas d'`<input type="image">`  dans ma page.
Page d'accueil eformation du CNED : 
https://eformation.cned.fr/login/cned/
(demande moi les login en perso pour que tu puisses y accéder)
![image](https://user-images.githubusercontent.com/41478857/114034504-87686880-987e-11eb-9605-47f3526fee24.png)
![image](https://user-images.githubusercontent.com/41478857/114034665-ad8e0880-987e-11eb-835a-fc400041f445.png)

**Comment by fhalna** [comment]
Fix
