### ISSUE TITLE
Référentiel de préférence

### ISSUE THREAD

**Issue by nmadeuf** [Tanaguru/tanaguru2020-engine#59]
Proposition d'évolution: 
Permettre de définir un référentiel de préférence afin que lorsqu'un utilisateur renseigne le formulaire pour lancer l'audit, le référentiel soit déjà choisi. 
Plusieurs possibilités: 

- au niveau du Projet
- au niveau du Contrat
- au niveau du Profil
- voir sur les 3 niveaux (peut nécessiter une priorisation Projet > Contrat > Profil)

**Comment by fhalna** [comment]
Amélioration réalisée
