### ISSUE TITLE
Audit de site en erreur (javascript error: this.each is not a function)

### ISSUE THREAD

**Issue by pbq** [Tanaguru/tanaguru2020-engine#63]
bonjour, 
je rencontre une erreur sur un audit du site suivant:
https://salonenligne.pole-emploi.fr/candidat/

le rappel des paramètres de l’audit:

> Audit parameters
>   Audit type : Page audit
>   Browser used to perform the audit : Google Chrome
>   Wait time : 500
>   Screenshots : No
>   Screen resolution : 1920 

à l’issue de l’audit, on obtient les logs suivants:
``` 
1. INFO - [27-04-2021 19:36] Audit created for scope PAGE
2. INFO - [27-04-2021 19:36] Tests script for audit created
3. INFO - [27-04-2021 19:36] Audit start
4. ERROR - [27-04-2021 19:36] Error during script execution on page https://salonenligne.pole-emploi.fr/candidat/ javascript error: this.each is not a function (Session info: headless chrome=88.0.4324.182) Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: host: 'tanaguru-8dfc4bbb8-8lnbg', ip: '19.0.67.143', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-136-generic', java.version: '11.0.10' Driver info: org.openqa.selenium.chrome.ChromeDriver Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: /tmp/.com.google.Chrome.P9WP6z}, goog:chromeOptions: {debuggerAddress: localhost:34081}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(manual, ssl=proxyaws...., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true} Session ID: 2b6aa692553fb1e7cf5590a35c44456c

5. ERROR - [27-04-2021 19:36] Audit failed because it does not contain pages
6. INFO - [27-04-2021 19:36] Audit end 
```

information complémentaire:
l’audit se réalise correctement si on utilise le moteur firefox avec 90 anomalies retournées.

**Comment by rcharre** [comment]
Bonjour,

En me renseignant un peu sur le sujet, j'ai pu trouver des sources indiquant qu'il s'agit d'un problème de chromium sur les sites modifiant :  Array.prototype object en utilisant des librairies comme prototype.js

Est ce le cas ici ?

Bien cordialement

Raphaël CHARRE

**Comment by fhalna** [comment]
les audits fonctionne depuis notre plateforme (via chrome). [Voir résultat d'audit](https://dev.tanaguru.com/#/audits/430/pages/4886/932730710)

**Comment by pbq** [comment]
> Bonjour,
> 
> En me renseignant un peu sur le sujet, j'ai pu trouver des sources indiquant qu'il s'agit d'un problème de chromium sur les sites modifiant : Array.prototype object en utilisant des librairies comme prototype.js
> 
> Est ce le cas ici ?
> 
> Bien cordialement
> 
> Raphaël CHARRE

Bonjour Raphaël, effectivement l'équipe utilise bien la librairie prototype1.7.js.

Mais si les audits passent depuis votre plateforme, le problème est peut être ailleurs.
Merci à vous deux.

Pierre

**Comment by pbq** [comment]
bonjour, 
avec le déploiement de la dernière image de l'engine, le problème est bien corrigé.

Merci beaucoup.

**Comment by RidLam** [comment]
Hello,
@pbq  est ce que vous pouvez rouvrir ce ticket ? car j'ai la même error : `Audit failed because it does not contain pages` et j'ai pas trouvé la solution 

J'utilises Tanaguru pour auditer un étapier ,le type d'audit est un scenario, j'ai utilisé Selenium IDE et firefox pour enregistrer le scénario et quand je lance l'audit j'ai l'error au-dessus 

**Audit parameters**

- Audit type : Scenario audit
- Browser used to perform the audit : Mozilla Firefox
- Wait time : 500
- Screenshots : No
- Screen resolution : 1920
- Main guideline : RGAA4.1(rgaa4.1)
- Guideline(s) used : RGAA4.1(rgaa4.1)

Je reste à votre disposition pour plus d'infos 

Merci pour votre aide

**Comment by fhalna** [comment]
Bonjour,

cela vient généralement du fait que votre serveur Tanaguru Engine ne peut atteindre la page à auditer. il faut s'assurer de cela avant de lancer l'audit.
