### ISSUE TITLE
Audit de site en erreur (cannot determine loading status from tab crashed)

### ISSUE THREAD

**Issue by pbq** [Tanaguru/tanaguru2020-engine#69]
Bonjour,
je rencontre une erreur sur un audit du site suivant:
https://www.lelab.pole-emploi.fr/

le rappel des paramètres de l’audit:

Audit parameters
Audit type : Page audit
Browser used to perform the audit : Google Chrome
Wait time : 500
Screenshots : Yes
Screen resolution : 1920

à l’issue de l’audit, on obtient les logs suivants:
```
1. INFO - [18-05-2021 14:48] Audit created for scope PAGE

2. INFO - [18-05-2021 14:48] Tests script for audit created

3. INFO - [18-05-2021 14:48] Audit start

4. ERROR - [18-05-2021 14:48] Error happened while auditing page https://www.lelab.pole-emploi.fr/ : unknown error: session deleted because of page crash from unknown error: cannot determine loading status from tab crashed (Session info: headless chrome=88.0.4324.182) Build info: version: 'unknown', revision: 'unknown', time: 'unknown' System info: host: 'tanaguru-58977d6948-4bvzj', ip: '19.0.31.36', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-136-generic', java.version: '11.0.10' Driver info: org.openqa.selenium.chrome.ChromeDriver Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 88.0.4324.182, chrome: {chromedriverVersion: 88.0.4324.96 (68dba2d8a0b14..., userDataDir: /tmp/.com.google.Chrome.aus0jR}, goog:chromeOptions: {debuggerAddress: localhost:37155}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(manual, ssl=proxyaws...., setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true} Session ID: 58676ddf5c6b180bfe1c7a109c51801f

5. ERROR - [18-05-2021 14:48] Audit failed because it does not contain pages

6. INFO - [18-05-2021 14:48] Audit end
```

L’audit se réalise correctement si on utilise le moteur firefox avec 8 anomalies retournées.

**Comment by rcharre** [comment]
Bonjour,

Peux-tu verifier que le conteneur docker est bien lancé avec le volume "/dev/shm:/dev/shm" de monté ou que le parametre "--shm-size 2g" est bien présent sur le conteneur.

Merci pour ton retour.

Raphaël CHARRE

**Comment by pbq** [comment]
Bonjour Raphaël, je vais vérifier le conteneur docker déployé.

Je reviens vers toi dès que possible.
Pierre

**Comment by pbq** [comment]
Bonjour Raphaël, sur Kubernetes, par défaut la mémoire partagée est à 64mb il me semble.
Je vais tâcher d'augmenter la taille de ce volume.

Pierre

**Comment by pbq** [comment]
Merci Raphaël pour l'astuce. 
Effectivement, j'ai poussé la quantité de mémoire allouée pour le pod sous K8S et l'audit sous chrome est désormais passant.

Pierre
