### ISSUE TITLE
[Audit de site] Champs url inclusion ne semble pas marcher sur https://act-rules.github.io/rules/

### ISSUE THREAD

**Issue by rcharre** [Tanaguru/tanaguru2020-engine#79]
Lors d'un audit sur https://act-rules.github.io/rules/
En remplissant le champs "inclusion url" avec : https://act-rules.github.io/rules/
L'audit ne remonte qu'une seul page

**Comment by lpedrau** [comment]
Le champ "inclusion url" attend une expression régulière, soit:  https:\/\/act-rules.github.io\/rules\/.*
L'audit remonte alors toutes les pages avec l'url commençant par https://act-rules.github.io/rules/
Action : modification côté webapp pour préciser sur le champ que c'est une expression régulière qui est attendue
